public with sharing class DemoApex {
   
    public static void method1(){

        Boolean isActive=true;
        System.debug('Boolean value is:'+isActive);
    }

    public static void method2(){

        String fname='Parth',lname='Adik';
        System.debug('Name:'+ fname +' '+lname);
    }
    public static void method3(){

        ID accId='001dM00000M7WkxQAF';
        System.debug('ID:'+accId);
    }
}